# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRAa9LiJ40OJkKbMb6RMJxfRDTXDDa9f
"""

!pip install pykeen

!pip install rdflib

from google.colab import files

uploaded = files.upload()

# TD5: Knowledge Graph Embedding (PyKEEN Version)
from rdflib import Graph
import random
from pykeen.pipeline import pipeline
from pykeen.triples import TriplesFactory
import pandas as pd

# --------------------------
# Step 1: Load TD4 Knowledge Graph
# --------------------------
g = Graph()
g.parse("td4_kb_final.ttl", format="turtle")

triples = []
for s, p, o in g:
    triples.append((str(s), str(p), str(o)))

# --------------------------
# Step 2: Split Train / Valid / Test (8:1:1)
# --------------------------
random.shuffle(triples)
n = len(triples)
train_triples = triples[:int(0.8*n)]
valid_triples = triples[int(0.8*n):int(0.9*n)]
test_triples  = triples[int(0.9*n):]

# --------------------------
# Step 3: Save as required KGE format
# --------------------------
def save_txt(data, path):
    with open(path, "w", encoding="utf-8") as f:
        for s,p,o in data:
            f.write(f"{s}\t{p}\t{o}\n")

save_txt(train_triples, "train.txt")
save_txt(valid_triples, "valid.txt")
save_txt(test_triples, "test.txt")

print("==================================================")
print("✅ TD5 Knowledge Graph Embedding Ready")
print("==================================================")
print(f"Total Triples Loaded: {len(triples)}")
print(f"Train: {len(train_triples)} | Valid: {len(valid_triples)} | Test: {len(test_triples)}")
print("==================================================")

# --------------------------
# Step 4: Load triples for PyKEEN
# --------------------------
train = TriplesFactory.from_path("train.txt")
valid = TriplesFactory.from_path("valid.txt")
test  = TriplesFactory.from_path("test.txt")

# --------------------------
# Step 5: Train TransE model
# --------------------------
result = pipeline(
    training=train,
    validation=valid,
    testing=test,
    model="TransE",
    model_kwargs=dict(embedding_dim=100),
    optimizer="adam",
    optimizer_kwargs=dict(lr=0.001),
    training_kwargs=dict(num_epochs=50, batch_size=32),
    negative_sampler="bernoulli",
    evaluator_kwargs=dict(filtered=True)
)

# --------------------------
# Step 6: Extract metrics
# --------------------------
metrics = result.metric_results
data = []

for side in ["head", "tail"]:
    data.append([
        side,
        metrics.get_metric(f"{side}.realistic.mrr"),
        metrics.get_metric(f"{side}.realistic.hits_at_1"),
        metrics.get_metric(f"{side}.realistic.hits_at_3"),
        metrics.get_metric(f"{side}.realistic.hits_at_10"),
    ])

df_metrics = pd.DataFrame(data, columns=["Prediction", "MRR", "Hits@1", "Hits@3", "Hits@10"])

print("📊 TransE Model Evaluation Results (filtered metrics):")
print(df_metrics)

# --------------------------
# Step 7: Save model and metrics
# --------------------------
result.save_to_directory("trained_transe_model")
df_metrics.to_csv("td5_results.csv", index=False)

from google.colab import files
files.download("td5_results.csv")